resolver: lts-9.0
flags:
  xmonad-contrib:
    testing: false
    use_xft: true
  xmonad:
    testing: false
    use_xft: true
extra-deps:
  - show-type-0.1.1
  - xmonad-0.13
  - xmonad-contrib-0.13
# packages:
#   - ../../dev/xmonad-contrib
#   - ../../dev/xmonad
#   - ./